### ISSUE TITLE
[BUG] userDao 함수 호출시 에러

### ISSUE THREAD

**Issue by ChoHadam** [A-fume/A.fume.Server#256]
## 버그 묘사
reviewService.js내에 신고 기능을 위해 userDao.ts를 import한 후 userDao.readByIdx를 호출하고, 신고 기능 API를 호출했더니 아래와 같은 에러가 났다.

## 버그 재현
```
TypeError: userDao.readByIdx is not a function
    at _callee9$ (C:\Users\hadam\Desktop\A.fume.Server\dist\service\ReviewService.js:520:28)
    at tryCatch (C:\Users\hadam\Desktop\A.fume.Server\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\hadam\Desktop\A.fume.Server\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\hadam\Desktop\A.fume.Server\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\hadam\Desktop\A.fume.Server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\hadam\Desktop\A.fume.Server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\hadam\Desktop\A.fume.Server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\hadam\Desktop\A.fume.Server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.reportReview (C:\Users\hadam\Desktop\A.fume.Server\dist\service\ReviewService.js:551:19)
```

**Comment by heesung6701** [comment]
UserDao가 Class로 변경되면서 new UserDao() 생성해서 사용하셔야 합니다!

**Comment by heesung6701** [comment]
```
import UserDao from '@dao/UserDao';
this.userDao = new UserDao()
this.userDao.readByIdx(userIdx);
```

**Comment by heesung6701** [comment]
확인하고 이상 없으면 close 해주세요
@ChoHadam
